#ifndef LIBTHETROPOSPHERE_GLOBAL_H
#define LIBTHETROPOSPHERE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBTHETROPOSPHERE_LIBRARY)
    #define LIBTHETROPOSPHERE_EXPORT Q_DECL_EXPORT
#else
    #define LIBTHETROPOSPHERE_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBTHETROPOSPHERE_GLOBAL_H
